### ISSUE TITLE
页面切换滚动条记忆问题？

### ISSUE THREAD

**Issue by zhuanglong** [maqi1520/nextjs-tailwind-blog#4]
开发环境，页面切换后滚动条没有恢复到上一次的浏览的位置，如图，再次切回文章详情页滚动到了顶部。

![动画2](https://user-images.githubusercontent.com/19422011/221134504-4453c537-d215-4a03-ac44-3e1c320d225c.gif)

作者 blog，切换后都恢复到之前浏览的位置。

![动画](https://user-images.githubusercontent.com/19422011/221134113-19dd2a8f-a4dd-4b47-84ba-a9c9d4dbc7ce.gif)

**Comment by maqi1520** [comment]
滚动位置记忆，这个功能是未实现的，可以将 html  上的  scroll-smooth 样式去除，这样页面切换的时候就不会有滚动
